name: Ruby Gem

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7]
        rails: ['5.0', '5.1', '5.2', '6.0']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle install
      run: bundle install
      env:
        BUNDLE_GEMFILE: "test/gemfiles/${{ matrix.rails }}.gemfile"
    - run: bundle exec rake

